// Mapowanie nazw krajów z angielskiego na polski
export const countryNamesMap: Record<string, string> = {
  // Europa
  Poland: "Polska",
  Germany: "Niemcy",
  France: "Francja",
  Spain: "Hiszpania",
  Italy: "Włochy",
  "United Kingdom": "Wielka Brytania",
  Ukraine: "Ukraina",
  Russia: "Rosja",
  Turkey: "Turcja",
  Greece: "Grecja",
  Portugal: "Portugalia",
  Netherlands: "Holandia",
  Belgium: "Belgia",
  "Czech Republic": "Czechy",
  Austria: "Austria",
  Switzerland: "Szwajcaria",
  Sweden: "Szwecja",
  Norway: "Norwegia",
  Denmark: "Dania",
  Finland: "Finlandia",
  Romania: "Rumunia",
  Hungary: "Węgry",
  Serbia: "Serbia",
  Croatia: "Chorwacja",
  Slovakia: "Słowacja",
  Bulgaria: "Bułgaria",
  Belarus: "Białoruś",
  Lithuania: "Litwa",
  Latvia: "Łotwa",
  Estonia: "Estonia",
  Ireland: "Irlandia",
  Iceland: "Islandia",
  Albania: "Albania",
  Slovenia: "Słowenia",
  "Bosnia and Herzegovina": "Bośnia i Hercegowina",
  "North Macedonia": "Macedonia Północna",
  Montenegro: "Czarnogóra",
  Moldova: "Mołdawia",
  Kosovo: "Kosowo",
  Malta: "Malta",
  Luxembourg: "Luksemburg",
  Cyprus: "Cypr",
  Andorra: "Andora",
  Monaco: "Monako",
  "San Marino": "San Marino",
  "Vatican City": "Watykan",
  Liechtenstein: "Liechtenstein",

  // Azja
  China: "Chiny",
  India: "Indie",
  Japan: "Japonia",
  "South Korea": "Korea Południowa",
  "North Korea": "Korea Północna",
  Indonesia: "Indonezja",
  Pakistan: "Pakistan",
  Bangladesh: "Bangladesz",
  Vietnam: "Wietnam",
  Thailand: "Tajlandia",
  Iran: "Iran",
  Iraq: "Irak",
  Afghanistan: "Afganistan",
  "Saudi Arabia": "Arabia Saudyjska",
  Israel: "Izrael",
  Syria: "Syria",
  Yemen: "Jemen",
  Jordan: "Jordania",
  Lebanon: "Liban",
  "United Arab Emirates": "Zjednoczone Emiraty Arabskie",
  Kazakhstan: "Kazachstan",
  Uzbekistan: "Uzbekistan",
  Mongolia: "Mongolia",
  Myanmar: "Mjanma",
  Malaysia: "Malezja",
  Singapore: "Singapur",
  Philippines: "Filipiny",
  Cambodia: "Kambodża",
  Laos: "Laos",
  Nepal: "Nepal",
  "Sri Lanka": "Sri Lanka",
  Taiwan: "Tajwan",
  Armenia: "Armenia",
  Azerbaijan: "Azerbejdżan",
  Georgia: "Gruzja",
  Kuwait: "Kuwejt",
  Oman: "Oman",
  Qatar: "Katar",
  Bahrain: "Bahrajn",
  Tajikistan: "Tadżykistan",
  Kyrgyzstan: "Kirgistan",
  Turkmenistan: "Turkmenistan",
  Bhutan: "Bhutan",
  Maldives: "Malediwy",
  Brunei: "Brunei",
  "Timor-Leste": "Timor Wschodni",

  // Ameryka Północna
  "United States of America": "Stany Zjednoczone",
  Canada: "Kanada",
  Mexico: "Meksyk",
  Cuba: "Kuba",
  Guatemala: "Gwatemala",
  Honduras: "Honduras",
  Nicaragua: "Nikaragua",
  "Costa Rica": "Kostaryka",
  Panama: "Panama",
  "Dominican Republic": "Dominikana",
  Haiti: "Haiti",
  Jamaica: "Jamajka",
  "El Salvador": "Salwador",
  Belize: "Belize",
  "Trinidad and Tobago": "Trynidad i Tobago",
  Bahamas: "Bahamy",
  Barbados: "Barbados",
  Grenada: "Grenada",
  "Saint Lucia": "Saint Lucia",
  "Saint Vincent and the Grenadines": "Saint Vincent i Grenadyny",
  "Antigua and Barbuda": "Antigua i Barbuda",
  Dominica: "Dominika",
  "Saint Kitts and Nevis": "Saint Kitts i Nevis",

  // Ameryka Południowa
  Brazil: "Brazylia",
  Argentina: "Argentyna",
  Chile: "Chile",
  Colombia: "Kolumbia",
  Peru: "Peru",
  Venezuela: "Wenezuela",
  Ecuador: "Ekwador",
  Bolivia: "Boliwia",
  Paraguay: "Paragwaj",
  Uruguay: "Urugwaj",
  Guyana: "Gujana",
  Suriname: "Surinam",
  "French Guiana": "Gujana Francuska",

  // Afryka
  Nigeria: "Nigeria",
  Ethiopia: "Etiopia",
  Egypt: "Egipt",
  "South Africa": "RPA",
  Kenya: "Kenia",
  Tanzania: "Tanzania",
  Algeria: "Algieria",
  Morocco: "Maroko",
  Uganda: "Uganda",
  Ghana: "Ghana",
  Mozambique: "Mozambik",
  Madagascar: "Madagaskar",
  Angola: "Angola",
  Cameroon: "Kamerun",
  Niger: "Niger",
  Mali: "Mali",
  "Burkina Faso": "Burkina Faso",
  Malawi: "Malawi",
  Zambia: "Zambia",
  Somalia: "Somalia",
  Senegal: "Senegal",
  Chad: "Czad",
  Zimbabwe: "Zimbabwe",
  Guinea: "Gwinea",
  Rwanda: "Rwanda",
  Benin: "Benin",
  Tunisia: "Tunezja",
  Burundi: "Burundi",
  "South Sudan": "Sudan Południowy",
  Togo: "Togo",
  "Sierra Leone": "Sierra Leone",
  Libya: "Libia",
  Liberia: "Liberia",
  Mauritania: "Mauretania",
  "Central African Republic": "Republika Środkowoafrykańska",
  Eritrea: "Erytrea",
  Gambia: "Gambia",
  Botswana: "Botswana",
  Namibia: "Namibia",
  Gabon: "Gabon",
  Lesotho: "Lesotho",
  "Guinea-Bissau": "Gwinea Bissau",
  "Equatorial Guinea": "Gwinea Równikowa",
  Mauritius: "Mauritius",
  Eswatini: "Eswatini",
  Djibouti: "Dżibuti",
  Comoros: "Komory",
  "Cape Verde": "Republika Zielonego Przylądka",
  "São Tomé and Príncipe": "Wyspy Świętego Tomasza i Książęca",
  Seychelles: "Seszele",
  Sudan: "Sudan",
  "Ivory Coast": "Wybrzeże Kości Słoniowej",
  "Dem. Rep. Congo": "Demokratyczna Republika Konga",
  Congo: "Kongo",

  // Oceania
  Australia: "Australia",
  "New Zealand": "Nowa Zelandia",
  "Papua New Guinea": "Papua-Nowa Gwinea",
  Fiji: "Fidżi",
  "Solomon Islands": "Wyspy Salomona",
  Vanuatu: "Vanuatu",
  Samoa: "Samoa",
  Kiribati: "Kiribati",
  Tonga: "Tonga",
  Micronesia: "Mikronezja",
  Palau: "Palau",
  "Marshall Islands": "Wyspy Marshalla",
  Nauru: "Nauru",
  Tuvalu: "Tuvalu",
}

// Funkcja pomocnicza do tłumaczenia nazw
export function translateCountryName(englishName: string): string {
  return countryNamesMap[englishName] || englishName
}
